services:
  backend:
    build: .
    container_name: znak_backend
    restart: unless-stopped
    volumes:
      - ./beckend:/app
      - sqlite_data:/app/beckend
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8001:8000"
    environment:
      - DEBUG=False
      - DOCKER_ENV=True
      - PRODUCTION=True
      - ALLOWED_HOSTS=test.zastava-86.ru,localhost,127.0.0.1
      - DATA_UPLOAD_MAX_SIZE=52428800
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      args:
        - VUE_APP_API_URL=https://test.zastava-86.ru/api/
    container_name: znak_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
  sqlite_data:
