# Generated by Django 4.2 on 2026-04-30 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('znakapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Мой значок', max_length=200, verbose_name='Название проекта')),
                ('shape_type', models.CharField(choices=[('circle', 'Круг'), ('square', 'Квадрат'), ('star', 'Звезда'), ('shield', 'Щит'), ('heart', 'Сердце'), ('oval', 'Овал'), ('hexagon', 'Шестиугольник'), ('cross', 'Крест')], default='circle', max_length=20, verbose_name='Форма')),
                ('diameter_mm', models.FloatField(default=44, verbose_name='Диаметр (мм)')),
                ('orientation', models.CharField(choices=[('portrait', 'Портретная'), ('landscape', 'Альбомная')], default='portrait', max_length=10, verbose_name='Ориентация')),
                ('shapes_data', models.JSONField(default=dict, verbose_name='Данные изображений')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='badge_previews/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект значка',
                'verbose_name_plural': 'Проекты значков',
                'ordering': ['-updated_at'],
            },
        ),
    ]
